#!/usr/bin/env bash
# bootstrap-worktree.sh — make a fresh git worktree runnable for this project.
#
# The dispatcher runs this after every `git worktree add`. A bare worktree has
# tracked files only: no dependencies, no secrets, no generated code — and no
# tier-1 skill symlinks (gitignored symlinks never materialize in new
# worktrees). This script closes that gap. It must be IDEMPOTENT (it re-runs on
# worktree re-attach) and NON-INTERACTIVE (it runs unattended inside the loop).
#
# Usage: scripts/bootstrap-worktree.sh <target-worktree-path>
set -euo pipefail
WT="${1:?usage: bootstrap-worktree.sh <target-worktree-path>}"

# --- context-specs deterministic section (do not edit or remove) -------------
# Re-create the tier-1 skill/agent symlinks in the new worktree so headless
# skills resolve there. The `context-specs` CLI is installed globally (npm), and
# CONTEXT_SPECS_HOME tells it WHICH harness to link from — the dispatcher
# exports it; a human running this by hand exports their harness repo path.
# Idempotent and fast.
: "${CONTEXT_SPECS_HOME:?export CONTEXT_SPECS_HOME=<path to your harness repo>, or invoke via the harness}"
context-specs link "$WT"
# --- project-specific provisioning below (generated by /env-init) ------------

# [Generated per project by /env-init — typical steps, in order:
#  1. copy gitignored runtime files (.env, credentials) from the source checkout
#     (derive it via `git -C "$WT" rev-parse --git-common-dir` → its parent);
#     copy direction is ALWAYS source → worktree, never the reverse, never delete
#  2. install dependencies with the lockfile-frozen flavor (npm ci, uv sync, ...)
#  3. run codegen the project needs before it can run (prisma generate, ...)
# Every step gets a one-line comment saying what it provisions and why.]
